name: "Version bumper"

on:
    pull_request:
        branches:
            - main
        paths:
            - "python_project/**"
            - "pyproject.toml"

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}
                  fetch-depth: 0

            - name: Version bumper
              uses: apowis/pyproject-bump-version@v0.0.1
              with:
                  file_to_bump: "./pyproject.toml"
                  bump_type: "micro"
                  main_branch: "main"
                  python_version: "3.13"
